const fs = require('fs');
const c = fs.readFileSync('Чистовые слайды v3.3 — Проценты, пропорции, масштаб.md', 'utf8');
const m = c.match(/^### Слайд [^\n]*$/gm);
console.log('Total: ' + m.length);
console.log('First 8:');
console.log(m.slice(0, 8).join('\n'));
console.log('---');
const cnt = {};
m.forEach(x => { const n = x.match(/### Слайд ([0-9.]+)/)[1]; cnt[n] = (cnt[n] || 0) + 1; });
console.log('Conflicts:');
Object.keys(cnt).forEach(k => { if (cnt[k] > 1) console.log('  ' + k + ': ' + cnt[k]); });
